table revenue_forecast
	lineageTag: 52b502fa-c820-437a-9dd1-6b7b56853d37

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 498b9a5e-b409-42d8-beb7-5294e54a1333
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 35c0b1a5-f41d-428d-8273-f23280101d79
			defaultHierarchy: LocalDateTable_0697b8a9-1c3f-4f9e-97b4-a7fc8740bab7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column forecast_revenue
		dataType: double
		lineageTag: ee97a7ea-8ab7-4ff9-8077-e1c0d0f9768f
		summarizeBy: sum
		sourceColumn: forecast_revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition revenue_forecast = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\OLUWATOSIN OLUWASEUN\Downloads\customer-360-revenue-growth-analytics\powerbi\data\revenue_forecast.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"date", type date}, {"forecast_revenue", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

