table rfm_segment_summary
	lineageTag: 83eb4523-14bb-4aa9-bb1b-c75d579e15f7

	column customer_segment
		dataType: string
		lineageTag: b4665f56-74b2-4ddb-958e-2ad0a1125467
		summarizeBy: none
		sourceColumn: customer_segment

		annotation SummarizationSetBy = Automatic

	column customers
		dataType: int64
		formatString: 0
		lineageTag: fe988a1f-7bc8-49aa-b4ac-a4bb9ba98864
		summarizeBy: sum
		sourceColumn: customers

		annotation SummarizationSetBy = Automatic

	column avg_recency_days
		dataType: double
		lineageTag: 9f9a1e2a-a04c-4dd2-a405-2e5e26bf5158
		summarizeBy: sum
		sourceColumn: avg_recency_days

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column avg_frequency
		dataType: double
		lineageTag: bb18e193-2cc0-4706-933b-c8144d321055
		summarizeBy: sum
		sourceColumn: avg_frequency

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_revenue
		dataType: int64
		formatString: 0
		lineageTag: a3367daf-3195-4fd3-86f5-92059a50b214
		summarizeBy: sum
		sourceColumn: total_revenue

		annotation SummarizationSetBy = Automatic

	column avg_customer_value
		dataType: double
		lineageTag: 6d3962d0-21ea-4dd5-ae49-5d330d7f791a
		summarizeBy: sum
		sourceColumn: avg_customer_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column customer_share_pct
		dataType: double
		lineageTag: 0b02cc2f-c6e3-4400-afdb-846b2cba4224
		summarizeBy: sum
		sourceColumn: customer_share_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition rfm_segment_summary = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\OLUWATOSIN OLUWASEUN\Downloads\customer-360-revenue-growth-analytics\powerbi\data\rfm_segment_summary.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_segment", type text}, {"customers", Int64.Type}, {"avg_recency_days", type number}, {"avg_frequency", type number}, {"total_revenue", Int64.Type}, {"avg_customer_value", type number}, {"customer_share_pct", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

