table monthly_kpis
	lineageTag: a79cf0ea-e06e-4518-a3e2-33c65ede2b93

	column month
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1a0e4b12-3aa4-4ad1-aec7-0e933f635a09
		summarizeBy: none
		sourceColumn: month

		variation Variation
			isDefault
			relationship: 110456b5-b0bb-41f9-9a9f-7bfdff7d0160
			defaultHierarchy: LocalDateTable_599865bc-3d1f-4ce6-8218-59c5ad21bda8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column users
		dataType: int64
		formatString: 0
		lineageTag: c23677b0-8116-40e2-ba77-a23ac6a71205
		summarizeBy: sum
		sourceColumn: users

		annotation SummarizationSetBy = Automatic

	column purchasing_users
		dataType: int64
		formatString: 0
		lineageTag: 6f574934-d423-43d3-8103-35aae386e001
		summarizeBy: sum
		sourceColumn: purchasing_users

		annotation SummarizationSetBy = Automatic

	column purchases
		dataType: int64
		formatString: 0
		lineageTag: 47e44cfe-a825-483a-9cb7-d119859701a8
		summarizeBy: sum
		sourceColumn: purchases

		annotation SummarizationSetBy = Automatic

	column revenue
		dataType: int64
		formatString: 0
		lineageTag: c1ef4a57-bd5c-4b99-a522-e59d42dac613
		summarizeBy: sum
		sourceColumn: revenue

		annotation SummarizationSetBy = Automatic

	column customer_conversion_pct
		dataType: double
		lineageTag: 2af658bf-3b5e-4364-b166-993372ce1c18
		summarizeBy: sum
		sourceColumn: customer_conversion_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column avg_order_value
		dataType: double
		lineageTag: 86c2d4f1-a9dc-42f5-aa45-cc31443b5f37
		summarizeBy: sum
		sourceColumn: avg_order_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition monthly_kpis = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\OLUWATOSIN OLUWASEUN\Downloads\customer-360-revenue-growth-analytics\powerbi\data\monthly_kpis.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"month", type date}, {"users", Int64.Type}, {"purchasing_users", Int64.Type}, {"purchases", Int64.Type}, {"revenue", Int64.Type}, {"customer_conversion_pct", type number}, {"avg_order_value", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

