table acquisition_performance
	lineageTag: 8d786ed1-8a5d-432c-a920-1efc4a8a931d

	column source
		dataType: string
		lineageTag: 32f1bad8-920e-444b-9d08-efd6238856f6
		summarizeBy: none
		sourceColumn: source

		annotation SummarizationSetBy = Automatic

	column medium
		dataType: string
		lineageTag: 233d0481-5407-4e86-b2ba-1d372e53a6ef
		summarizeBy: none
		sourceColumn: medium

		annotation SummarizationSetBy = Automatic

	column users
		dataType: int64
		formatString: 0
		lineageTag: e008662f-eac8-410a-a938-e72c0c5e2662
		summarizeBy: sum
		sourceColumn: users

		annotation SummarizationSetBy = Automatic

	column purchasing_users
		dataType: int64
		formatString: 0
		lineageTag: 61550943-218d-4e12-a1b0-3855a8f80291
		summarizeBy: sum
		sourceColumn: purchasing_users

		annotation SummarizationSetBy = Automatic

	column purchase_events
		dataType: int64
		formatString: 0
		lineageTag: 475ccfed-7857-4183-b916-b67186ae936c
		summarizeBy: sum
		sourceColumn: purchase_events

		annotation SummarizationSetBy = Automatic

	column revenue
		dataType: int64
		formatString: 0
		lineageTag: c047e249-9a02-4ddb-8475-81f98c6d5b77
		summarizeBy: sum
		sourceColumn: revenue

		annotation SummarizationSetBy = Automatic

	column conversion_rate_pct
		dataType: double
		lineageTag: a678ea97-361e-45c3-8fda-c1664dbc605e
		summarizeBy: sum
		sourceColumn: conversion_rate_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column revenue_per_user
		dataType: double
		lineageTag: 982e4d11-0937-46c1-bf77-546acecce06e
		summarizeBy: sum
		sourceColumn: revenue_per_user

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition acquisition_performance = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\OLUWATOSIN OLUWASEUN\Downloads\customer-360-revenue-growth-analytics\powerbi\data\acquisition_performance.csv"),[Delimiter=",", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"source", type text}, {"medium", type text}, {"users", Int64.Type}, {"purchasing_users", Int64.Type}, {"purchase_events", Int64.Type}, {"revenue", Int64.Type}, {"conversion_rate_pct", type number}, {"revenue_per_user", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

