table cohort_retention
	lineageTag: 77b300c3-9c80-4c3c-afe2-a9195a5c5675

	column cohort_month
		dataType: dateTime
		formatString: Long Date
		lineageTag: ced12dcf-0e1b-47af-8204-40a1d02e1fd8
		summarizeBy: none
		sourceColumn: cohort_month

		variation Variation
			isDefault
			relationship: 120ba962-9fd8-4670-bf8e-0aef1dbb6a41
			defaultHierarchy: LocalDateTable_a5894d14-6953-4cce-8f69-58d6ba2a9034.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column activity_month
		dataType: dateTime
		formatString: Long Date
		lineageTag: f33f4b82-4e6a-4bf5-ba1b-cac0d5838be0
		summarizeBy: none
		sourceColumn: activity_month

		variation Variation
			isDefault
			relationship: 5643f841-8c25-4d6f-a1b0-1862aab77c73
			defaultHierarchy: LocalDateTable_bb20f19e-f18b-4466-a0b9-153eb528b20d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column months_since_acquisition
		dataType: int64
		formatString: 0
		lineageTag: 799a4490-8782-4ba6-91ae-e89bc203ccae
		summarizeBy: sum
		sourceColumn: months_since_acquisition

		annotation SummarizationSetBy = Automatic

	column cohort_size
		dataType: int64
		formatString: 0
		lineageTag: a58ee2f2-e206-4246-9b34-186d81881ebf
		summarizeBy: sum
		sourceColumn: cohort_size

		annotation SummarizationSetBy = Automatic

	column active_users
		dataType: int64
		formatString: 0
		lineageTag: a7d44553-6378-43e3-ab67-8a6d16d09ee8
		summarizeBy: sum
		sourceColumn: active_users

		annotation SummarizationSetBy = Automatic

	column retention_rate_pct
		dataType: double
		lineageTag: a07a8efd-6cd8-4448-bb7d-c509b8f48286
		summarizeBy: sum
		sourceColumn: retention_rate_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition cohort_retention = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\OLUWATOSIN OLUWASEUN\Downloads\customer-360-revenue-growth-analytics\powerbi\data\cohort_retention.csv"),[Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"cohort_month", type date}, {"activity_month", type date}, {"months_since_acquisition", Int64.Type}, {"cohort_size", Int64.Type}, {"active_users", Int64.Type}, {"retention_rate_pct", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

