table product_performance
	lineageTag: a6414022-47c4-4976-b9c6-b96d747544cf

	column item_name
		dataType: string
		lineageTag: 69a78dd2-c932-480d-b762-3873a0671e11
		summarizeBy: none
		sourceColumn: item_name

		annotation SummarizationSetBy = Automatic

	column item_category
		dataType: string
		lineageTag: 6edf2f9a-de1a-46f2-ac1d-fcb39ad60e3b
		summarizeBy: none
		sourceColumn: item_category

		annotation SummarizationSetBy = Automatic

	column buyers
		dataType: int64
		formatString: 0
		lineageTag: 5e1b6c22-a291-4f8a-828c-c0f6576db061
		summarizeBy: sum
		sourceColumn: buyers

		annotation SummarizationSetBy = Automatic

	column units_sold
		dataType: int64
		formatString: 0
		lineageTag: 9dff22ea-b482-4687-94ec-c4070dd52d51
		summarizeBy: sum
		sourceColumn: units_sold

		annotation SummarizationSetBy = Automatic

	column product_revenue
		dataType: int64
		formatString: 0
		lineageTag: 49536e09-fd5a-45be-9ee9-920bb692fec2
		summarizeBy: sum
		sourceColumn: product_revenue

		annotation SummarizationSetBy = Automatic

	partition product_performance = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\OLUWATOSIN OLUWASEUN\Downloads\customer-360-revenue-growth-analytics\powerbi\data\product_performance.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"item_name", type text}, {"item_category", type text}, {"buyers", Int64.Type}, {"units_sold", Int64.Type}, {"product_revenue", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

