table synthetic_ab_test
	lineageTag: 81dd6b1f-1935-49ab-9154-a15bc053c75f

	column variant
		dataType: string
		lineageTag: 375fe9b9-62b2-4ce0-b1ac-b41bbf779246
		summarizeBy: none
		sourceColumn: variant

		annotation SummarizationSetBy = Automatic

	column users
		dataType: int64
		formatString: 0
		lineageTag: b9e5989a-44e6-4441-a022-afe486401fb1
		summarizeBy: sum
		sourceColumn: users

		annotation SummarizationSetBy = Automatic

	column conversions
		dataType: int64
		formatString: 0
		lineageTag: ae6be175-b182-4cc8-9c64-0c8f6f37b3ff
		summarizeBy: sum
		sourceColumn: conversions

		annotation SummarizationSetBy = Automatic

	column conversion_rate_pct
		dataType: double
		lineageTag: 6bc46cc7-4fa3-4409-a7bb-b5025989ff59
		summarizeBy: sum
		sourceColumn: conversion_rate_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column data_type
		dataType: string
		lineageTag: 1414ce7e-4033-4dad-ac9e-bc4d7d3f3b73
		summarizeBy: none
		sourceColumn: data_type

		annotation SummarizationSetBy = Automatic

	partition synthetic_ab_test = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\OLUWATOSIN OLUWASEUN\Downloads\customer-360-revenue-growth-analytics\powerbi\data\synthetic_ab_test.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"variant", type text}, {"users", Int64.Type}, {"conversions", Int64.Type}, {"conversion_rate_pct", type number}, {"data_type", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

